name: test
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch::torchvision=0.16
  - pytorch::pytorch=2.1
  - captum=0.6.0
  - numpy=1.26.3
  - pyyaml=6.0.1
  - matplotlib=3.8.0
  - scipy=1.11.4
  - future=0.18.3
  - Jinja2=3.1.2
  - scikit-learn=1.3.0
  - pandas=2.1.4
  - jupyter=1.0.0
  - seaborn=0.12.2
  - pytorch-cuda=11.8.0
  - skorch=0.15.0
  - tudat-team::nrlmsise-00
